apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "desk-picker-frontend.fullname" . }}
  labels:
    app: {{ include "desk-picker-frontend.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "desk-picker-frontend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "desk-picker-frontend.name" . }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
