global:
  host: desk-picker.dev.sourcesense.com

backend:
  image:
    repository: raffaelecamanzo/local-build-images
    tag: desk-picker-backend-${GIT_COMMIT}
  ingress:
    hosts:
      - host: desk-picker.dev.sourcesense.com
        paths:
          - path: /api
            pathType: Prefix

frontend:
  image:
    repository: raffaelecamanzo/local-build-images
    tag: desk-picker-frontend-${GIT_COMMIT}
  ingress:
    hosts:
      - host: desk-picker.dev.sourcesense.com
        paths:
          - path: /
            pathType: Prefix
